### ISSUE TITLE
The meaning of round1 data

### ISSUE THREAD

**Issue by ZyangLee** [Raibows/Learn-to-Reason#2]
Hi, from your paper, I learned that you should "exam" your student befor training, and chatGPT corrected those wrong answers from student.  There are 8,193 questions in your "cqa.train.round1" json, but only 9,740 in cqa.  Do all those questions in your dataset come from the student who answered incorrectly?

**Comment by Raibows** [comment]
Hi, 

`cqa.train.round1.json` is the collected training data of round 1. As explained in the second paragraph of Sec 3.4, in the initial round, we will try to cover the whole training set instead of the wrong ones. Please also refer to Algorithm 1.

**Comment by ZyangLee** [comment]
I understand completely. Thanks for the detailed response.
